export enum WidgetType {
    PUSH_STYLE = "PUSH_STYLE",
    PUSH_STYLE_OLD = "native",
    EMBEDDED_BANNER = "EMBEDDED_BANNER",
    EMBEDDED_BANNER_OLD = "banner",
    INTERSTITIAL_BANNER = "INTERSTITIAL_BANNER",
    INTERSTITIAL_VIDEO = "INTERSTITIAL_VIDEO",
}

export type WidgetAdTypes = WidgetType.PUSH_STYLE | WidgetType.EMBEDDED_BANNER | WidgetType.INTERSTITIAL_BANNER | WidgetType.INTERSTITIAL_VIDEO;